# Generated by Django 2.0 on 2019-03-10 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='address',
            field=models.CharField(default=1, max_length=500, verbose_name='地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userip',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='访问时间'),
            preserve_default=False,
        ),
    ]
