# Generated by Django 2.0 on 2019-01-26 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_imageslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100, verbose_name='友链名称')),
                ('link_href', models.CharField(max_length=200, verbose_name='友链地址')),
                ('link_pic', models.CharField(max_length=200, verbose_name='友链图标地址')),
                ('link_content', models.TextField(verbose_name='友链的描述')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imageslist',
            options={'verbose_name': '背景图片详情列表', 'verbose_name_plural': '背景图片详情列表'},
        ),
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '文章的每日阅读量', 'verbose_name_plural': '文章的每日阅读量'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '文章的累计阅读量', 'verbose_name_plural': '文章的累计阅读量'},
        ),
        migrations.AlterField(
            model_name='imageslist',
            name='pic',
            field=models.CharField(max_length=200, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
