# Generated by Django 2.0 on 2019-01-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20190126_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslist',
            name='link_content',
            field=models.TextField(blank=True, verbose_name='友链的描述'),
        ),
        migrations.AlterField(
            model_name='linkslist',
            name='link_pic',
            field=models.CharField(blank=True, max_length=200, verbose_name='友链图标地址'),
        ),
    ]
