# Generated by Django 2.0 on 2019-03-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0004_auto_20190126_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkslist',
            options={'verbose_name': '友链详情列表', 'verbose_name_plural': '友链详情列表'},
        ),
    ]
