# Generated by Django 2.0 on 2019-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20190310_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslist',
            name='pic',
            field=models.ImageField(max_length=500, upload_to='img/%Y/%m/%d', verbose_name='图片地址'),
        ),
    ]
