# Generated by Django 2.0 on 2019-01-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190106_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.CharField(default=1, max_length=500, verbose_name='文章缩略图'),
            preserve_default=False,
        ),
    ]
