# Generated by Django 2.0 on 2019-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190119_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(max_length=500, upload_to='img/%Y/%m/%d', verbose_name='缩略图'),
        ),
    ]
